version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.8.0

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          command: |
            git config --global user.email "fkrmtleo12@gmail.com"
            git config --global user.name "yesdoing"
            yarn run deploy