version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.8.0

    working_directory: ~/yes-player

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "fkrmtleo12@gmail.com"
            git config user.name "yesdoing"
      - add_ssh_keys:
          fingerprints:
            - "77:49:c5:d1:11:d5:0c:5e:61:ab:d2:46:0e:af:1c:5e"

      - run: yarn run deploy

      