version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.8.0

    working_directory: ~/yes-player

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "fkrmtleo12@gmail.com"
            git config user.name "yesdoing"
      - add_ssh_keys:
          fingerprints:
            - "99:28:4a:08:87:06:d7:d6:32:32:95:1f:90:46:a4:7f:97:4a:38:e1"

      - run: yarn run deploy

      